### ISSUE TITLE
buy/cancel

### ISSUE THREAD

**Issue by BatmanPDX** [ignaciop000/binance-traderBot#1]
The bot seems to set a buy order and then immediately cancels it:
_________________________________________________________________________________
TNBBTC : Buy order created id:11264187, quantity:215.00000000, buyPrice:0.00000510, Take profit aprox :0.00000530
Profit loss, called order, 11264187
Buy order fail (Not filled) Cancel order...
TNBBTC : Buy order created id:11264189, quantity:215.00000000, buyPrice:0.00000510, Take profit aprox :0.00000530
Profit loss, called order, 11264189
Buy order fail (Not filled) Cancel order...
TNBBTC : Buy order created id:11264190, quantity:215.00000000, buyPrice:0.00000510, Take profit aprox :0.00000530
Profit loss, called order, 11264190
Buy order fail (Not filled) Cancel order...
TNBBTC : Buy order created id:11264191, quantity:215.00000000, buyPrice:0.00000510, Take profit aprox :0.00000530
Profit loss, called order, 11264191
Buy order fail (Not filled) Cancel order...
____________________________________________________________________________________

It completely ignores the wait_time:
symbol:'TNBBTC',
	quantity:0,
	stop_loss:0,
	mode:'profit',
	profit:1.0,
	increasing:0.00000001,
	decreasing:0.00000001,
	loop:0,
	wait_time:180.0,
	prints: 1,

**Comment by BatmanPDX** [comment]
Has anyone else ran into this issue?

**Comment by ignaciop000** [comment]
The wait time is now ok. I forgotten to multiply per 1000.

**Comment by mistersms** [comment]
hello,
i am sorry, but i still have this error.

i am running the newest trading.js with multiplier of 1000 of wait_time.

i have also acitvated the debug: true in my coins.js, but i can only see the normal logging lines.

this is my logging/console output:

-snip-
Symbol: PPTBTC Profit: 0.21 Expected Profit: 0.90 ASK: 0.00159450 BID: 0.00159030 Commission: 0.00050000 profitSelling 0.00160541
Symbol: PPTBTC Profit: 0.21 Expected Profit: 0.90 ASK: 0.00159450 BID: 0.00159040 Commission: 0.00050000 profitSelling 0.00160551
Symbol: PPTBTC Profit: 1.03 Expected Profit: 0.90 ASK: 0.00160950 BID: 0.00159230 Commission: 0.00050000 profitSelling 0.00160743
PPTBTC : Buy order created id:20385280, quantity:2.00000000, buyPrice:0.00159240, Take profit aprox :0.00160743
Profit loss, called order, 20385280
Buy order fail (Not filled) Cancel order...
Symbol: PPTBTC Profit: 0.65 Expected Profit: 0.90 ASK: 0.00160920 BID: 0.00159800 Commission: 0.00050000 profitSelling 0.00161318
Symbol: PPTBTC Profit: 0.38 Expected Profit: 0.90 ASK: 0.00160480 BID: 0.00159800 Commission: 0.00050000 profitSelling 0.00161318
Symbol: PPTBTC Profit: 0.68 Expected Profit: 0.90 ASK: 0.00160480 BID: 0.00159320 Commission: 0.00050000 profitSelling 0.00160834
-snip-

if i buy manually with binance app with the same amount i have no problems.

need help.... thx

**Comment by mistersms** [comment]
debug log is active, because i can see the following lines in the console:

-snip-
Symbol: PPTBTC Profit: 0.05 Expected Profit: 0.90 ASK: 0.00154890 BID: 0.00154730 Commission: 0.00050000 profitSelling 0.00156200
Symbol: PPTBTC Profit: 0.06 Expected Profit: 0.90 ASK: 0.00154890 BID: 0.00154720 Commission: 0.00050000 profitSelling 0.00156190
{ Error: connect ECONNREFUSED 52.222.173.15:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '52.222.173.15',
  port: 443,
  config:
   { adapter: [Function: httpAdapter],
-snip

but when the bot is trying to buy there is no advanced logging in the console, only normal output on console like this:

-snip-
Symbol: PPTBTC Profit: 0.07 Expected Profit: 0.80 ASK: 0.00147000 BID: 0.00146820 Commission: 0.00050000 profitSelling 0.00148068
Symbol: PPTBTC Profit: 0.88 Expected Profit: 0.80 ASK: 0.00148360 BID: 0.00147000 Commission: 0.00050000 profitSelling 0.00148249
PPTBTC : Buy order created id:20508325, quantity:2.00000000, buyPrice:0.00147010, Take profit aprox :0.00148249
Profit loss, called order, 20508325
Buy order fail (Not filled) Cancel order...
Symbol: PPTBTC Profit: 0.66 Expected Profit: 0.80 ASK: 0.00148070 BID: 0.00147030 Commission: 0.00050000 profitSelling 0.00148280
Symbol: PPTBTC Profit: 0.64 Expected Profit: 0.80 ASK: 0.00148060 BID: 0.00147040 Commission: 0.00050000 profitSelling 0.00148290
-snip-

so i dont know why the bot can not buy symbols.

is it possible to get more infos for cancelled buy orders?

thx

**Comment by mistersms** [comment]
@ignaciop000 is it possible to set/enable debug logging for buy/profit loss/called order actions?
thx
